### ISSUE TITLE
可以将消息中心全部改为静态方法吗

### ISSUE THREAD

**Issue by Meta404Dev** [qinyuanpei/UniEventDispatcher#1]
这样就可以不用单例了

**Comment by qinyuanpei** [comment]
理论上是可以的，你喜欢这样就自己改吧！

**Comment by Meta404Dev** [comment]
哈哈，非常感谢，这个消息机制很好用

**Comment by qinyuanpei** [comment]
那我要提醒你的是，你改成静态类以后就没有办法扩展了，如果我这里将主题和订阅者抽象出来，使用两个泛型参数来替代，那么我可以定义出各种各样的消息中心，这就不是静态类能提供的能力啦，你如果一定要这样搞，自己去改吧，抽空我将它扩展出来吧！
